### ISSUE TITLE
CERN: WOPI: Fix tus client upload for local storage in reva

### ISSUE THREAD

**Issue by LovisaLugnegard** [sciencemesh/sciencemesh#114]
Right now upload (both via PATCH and tus client) returns 501 - not implemented for local storage.

**Comment by ishank011** [comment]
@LovisaLugnegard could you point to how you're framing the requests? The tus client with approach works through the [CLI](https://github.com/cs3org/reva/blob/master/cmd/reva/upload.go#L142) tool with local storage.

**Comment by LovisaLugnegard** [comment]
https://github.com/cs3org/wopiserver/blob/cs3org/src/cs3iface.py Line 163 and onwards. 

Can you please show me how you do it?

**Comment by labkode** [comment]
@ishank011 @LovisaLugnegard perhaps the python implementation and the Go one doesn't behave the same or one implemented more advanced functionalities. Is clear that a part from TUS we need to have simple support for PUT/GET requests.

**Comment by ishank011** [comment]
@LovisaLugnegard I didn't go through the complete blob, but pretty sure we're supposed to call one of either Upload (the old upload protocol) or NewUpload (through tus). The [upload](https://github.com/cs3org/wopiserver/blob/cs3/src/cs3iface.py#L209) method mentioned here might be another virtual method of the library which would need to be implemented, which is why you're getting the 501. [This](https://github.com/cs3org/reva/blob/master/cmd/reva/upload.go) ideally is how the request should look like. Maybe we can have a call and go over how it would need to be ported to python. I'll go through the python tusclient module in the meantime.

@labkode Makes sense. I'd look at maybe creating a wrapper around this.

**Comment by LovisaLugnegard** [comment]
Yes, that's what I've looked at when trying to get the things working in py. But yes please, let's have a call next week.

**Comment by ishank011** [comment]
Sure. In the meantime, can you try [this](https://github.com/cs3org/reva/blob/7eb3948ba59cabb7bc54c31454e1bb42f2ded68a/cmd/reva/upload.go#L116)? This is how uploads used to happen before tus. You just need to make a PUT request to the URL you get from InitiateFileUpload where the body is the file data and you need to set [these](https://github.com/cs3org/reva/blob/7eb3948ba59cabb7bc54c31454e1bb42f2ded68a/cmd/reva/upload.go#L121) headers. We'll definitely have to make tus work, but you can use this in case you're blocked by this issue.

**Comment by LovisaLugnegard** [comment]
Sure will do it next week though need to fix a few things for the auth after a rebase...
The res.token is empty for me when calling InitiateFileUpload
