### ISSUE TITLE
Review new ScienceMesh website

### ISSUE THREAD

**Issue by labkode** [sciencemesh/sciencemesh#164]
Review the new website design and see if there anything we would like to change/add/remove

https://sciencemesh.github.io/sciencemesh-web/

Feedback on this document:
https://codimd.web.cern.ch/3K27vTU6QR6BvMeSZZ8XAQ#

**Comment by Daniel-WWU-IT** [comment]
@labkode I already added what, from my perspective, is still missing to the feedback document. I did send an email to Rita about how the "Join the Mesh" process should look like now, but didn't get back a reply yet.

WP2 is also working on some technical details, and you can see the progress here (not sure if you can access it, though):
- https://github.com/cs3m4eosc-wp2/sciencemesh-web
- https://github.com/cs3m4eosc-wp2/sciencemesh

I believe that you should have been notified about this by Ron... if not, maybe you should drop him an email. I wasn't involved in this due to holidays.

**Comment by labkode** [comment]
Thanks @Daniel-WWU-IT , yes I think your feedback is part of the new developer.sciencemesh.io
