### ISSUE TITLE
WWU: Deploy containerized version of Argo

### ISSUE THREAD

**Issue by labkode** [sciencemesh/sciencemesh#26]
Based on discussions held here:
https://github.com/sciencemesh/sciencemesh/issues/7

Create a container for deployment Argo as part of the IOP.

The container and kubernetes specification can be added here:
https://github.com/sciencemesh/sciencemesh/tree/master/k8s

**Comment by Daniel-WWU-IT** [comment]
This is becoming more and more unfeasible, to be honest. When trying to install a local version of ARGO, I had to realize that their repos are offline, and according to my EGI contact, they aren't supported anymore. I am currently looking into alternatives.

**Comment by labkode** [comment]
@Daniel-WWU-IT what a mess. In that case, we should move to something simpler.

Reva already exposes Prometheus metrics and using Grafana is straightforward to visualize any metrics we desire. @Daniel-WWU-IT what is your opinion on that?

**Comment by Daniel-WWU-IT** [comment]
@labkode Will look into those! My current idea is to use an existing solution for monitoring (Nagios would also be a candidate here, though not a cheap one I think) and add our own QoS-solution that aggregates results etc. on top of that. I will investigate into our options and gather some ideas. Maybe you could open a new issue for this? Like "Look for ARGO alternatives"?

**Comment by labkode** [comment]
@Daniel-WWU-IT the IOP platform already use Prometheus, unless there is a big advantage using Nagios we'll stick to it..

To close this issue, please write down the reasons using Argo is not feasible.

**Comment by Daniel-WWU-IT** [comment]
The problems with ARGO I see are as follows:
- It's rather complex and complicated
- Configuration is cumbersame and very error-prone
- ARGO consists of a multitude of different components that all have to be set up correctly in order to work together properly
- The ARGO repos are no longer supported by EGI; they simply don't exist anymore. This made installing and testing/evaluating ARGO impossible.
- Aggregation of results is limited to _availability_ and _reliability_; if we find out that these don't suffice, we'd need to add something on our own anyway
- If we won't use GOCDB, things become even more complicated
- Documentation is rather incomplete and not too helpful

**Comment by labkode** [comment]
Investigating Prometheus as alternative in #33
