### ISSUE TITLE
WWU: investigate Prometheus for metrics gathering for QoS

### ISSUE THREAD

**Issue by labkode** [sciencemesh/sciencemesh#33]
Reva will export the OCM and other application endpoints like WOPI. For QOS, synthetic test will be executed against the IOP of each partner to verify the desired functionality to obtain QoS metrics (availability, reliability).

The IOP (Reva) already exports metrics using Prometheus, so we should investigate this option first.

**Comment by Daniel-WWU-IT** [comment]
@labkode After investigating Prometheus, I think it serves our purposes quite well. Here are a few reasons why:

- Prometheus tracks multi-dimensional numeric time series (offers high flexibility)
- It allows one to define aggregation rules
- It offers an extensive API that can be used to query the gathered data
- It is well documented, very easy to set up, and configuration is also straight-forward
- Supports alerting in many customizable ways
- Hierarchical federation is also somewhat supported (one Prometheus server can use the data of another one)
- A Prometheus server is completely autonomous and doesn't rely on any other services
- Using Grafana (or even their own web UI), we can offer nice visual representations of all metrics

If using Prometheus, there will be several tasks to do, as it doesn't offer everything we will most likely need:

- Gather information about service endpoints/probes from GOCDB (or whatever we'll use)
- Represent the metrics in a hierarchical way
- Create aggregations (availability, reliability and maybe others) for services and entire sites
- Define rules on how to define a service/site status
- Take scheduled downtimes of services into account
- ... and surely more that will come up later

Unlike Nagios probes, Prometheus probes must use a client library, though I think this is acceptable; they also offer push gateways that can be used to circumvent that. Unlike ARGO, Prometheus actually works on numerical time series, so this gives us greater flexibility; it also tracks the UP state of each service, though, so we could use that as a very simple metric as well. Since Reva already comes with a Prometheus client, it totally makes sense to go for Prometheus as the underlying monitoring system. It will require us to write some services "on top" - as is also the case for using GOCDB -, but I believe that the additional effort is feasible.

**Comment by Daniel-WWU-IT** [comment]
@labkode I wrote some small Go scripts that 1) gather information about services to be monitored from GOCDB and exports those to Prometheus, which imports them via a service discovery service and 2) query some statistics from the monitored services and print them out. This works extremely well and was straightforward to do.

**Comment by labkode** [comment]
We'll use Prometheus to export metrics to local provider and adapt metrics to be sent to ARGO.
