### ISSUE TITLE
WWU: Identify suitability of ARGO for QoS

### ISSUE THREAD

**Issue by labkode** [sciencemesh/sciencemesh#7]
As a site administrator or sciencemesh manager I want to quickly have an overview of all the sites integrating the mesh.

For that to happen, I need to collect metrics from all the sites to monitorize their SLAs, KPIs and SLIs.

In the project proposal the EGI  ARGO system was proposed as a viable candidate. This task identifies the technical requirements for using ARGO:

* How can I send the data to it? What are the APIS, payloads (XML, JSON, ...).
* Can I deploy it?

Reva exports a Prometheus endpoint, what would be needed to export Reva metrics to ARGO?

Pointer: https://argo.egi.eu/

Some documentation:
https://argoeu.github.io/overview/

**Comment by Daniel-WWU-IT** [comment]
### Summary of ARGO ###
- A site offers one or more services which each come with various endpoints
- Captures the status of all services of the various sites in a mesh
- Topology of the mesh is usually defined via GOCDB (but one can write a new connector or use its API for this)
- A site is the sum of its services
- Offers a seemingly extensive Web API (data is XML); hard to understand though due to lack of real documentation
- The various endpoints of each service are monitored
- _What_ is being monitored can be configured and depends on the service type (not sure how these are defined; GOCDB comes with loads of default types)
- _How_ services are monitored is not clear yet, as the documentation is missing

#### General workflow of ARGO: ####
- Each endpoint is periodically probed
- The results of each probe (OK, Warning, Error, ...) are combined using a truth table into a service status (OK, Critical, ...)
- Based on this, the availability (uptime to total time ratio) and reliability (uptime to planned uptime ratio) are calculated for each service
- Service scores are accumulated for each site
- Workflow diagram: [QoS-Flow.pdf](https://github.com/sciencemesh/sciencemesh/files/4370114/QoS-Flow.pdf)

#### Issues/Open questions: ####
- ARGO seems to be rather complex
- Complicated and cumbersome configuration (as it seems)
- Unclear how service types and their endpoints are defined and queried; related to GOCDB open questions
- Also unclear how to define various metrics that are to be queried - but the idea of having definable metrics and how they are accumulated into a final "service status" is nice
- It might be difficult to get external data into ARGO; they offer ways to import reports, though

#### Final thoughts: ####
The workflow and concepts of ARGO seem to be really nice for QoS, especially since they are rather flexible; this means, of course, that we have to define rules and measures for each service type and how these are accumulated. The whole system is rather complex and complicated, though, especially since it is so interwoven with GOCDB. So it's necessary to get used to it more before judging its usefulness. Getting into contact with someone at EGI is an absolute necessity to continue.

**Comment by labkode** [comment]
@Daniel-WWU-IT Thanks Daniel for the nice wrap up. When you reach to EGI folks, ask them if they have any test system where we can add our services to start prototyping with their system? Also, inquire about the lack of documentation and they should provide you with examples.

Another alternative will be to deploy the technology locally as part of the IOP for testing purposes.
 
What alternatives we have as plan B if we see that integration with this service is far from ideal?

**Comment by Daniel-WWU-IT** [comment]
I am currently emailing with EGI about this; let's wait and see what they have to say.

ARGO can be deployed locally, though we haven't done this yet. We just got a copy of GOCDB running, which is a first start.

There is no real Plan B as of yet (except for writing something from scratch). I think it might be even more important to agree on whether ARGO's _workflow_ fits our purposes, or if we need something entirely else - then it is far easier to find alternatives :) ARGO at least gives us an idea of how monitoring and ultimately QoS could be done.

**Comment by Daniel-WWU-IT** [comment]
A quick update: It seems (really not 100% sure) that ARGO itself doesn't do the probing, it simply wants metrics data in a certain way which it then processes. One way to get that data into ARGO is to put a JSON file in a specific folder on the ARGO system, and a Cron job will process it later. The documentation is really not good at all, so I hope they will answer my email soon.

**Comment by labkode** [comment]
@Daniel-WWU-IT thanks. Would be interesting to know if they can fetch a URL with the expected JSON so we can expose it through REVA.

**Comment by Daniel-WWU-IT** [comment]
@labkode The currently undocumented ARGO Consumer seems to be responsible for collecting this data, so we'll have to wait till I get more information to be able to answer this (nothing so far). The compute engine (the workhorse of ARGO) has no API for this as it seems. But one could write a  service that accepts the JSON data and simply writes it as a file into ARGO's directory structure I think.

**Comment by Daniel-WWU-IT** [comment]
After some really helpful emails from EGI, here is what I was able to figure out:

- ARGO first needs some topology data; using GOCDB is the easiest way here (but not necessary)
- There is a dedicated component called POEM for defining metrics and probes
  - Probes must support the Nagios API
  - The ARGO monitoring engine uses this information to run the probes periodically
- External data can be imported using their messaging service (can't say how, but I was assured that it is possible)
- The ARGO compute engine uses above data to compute service states etc.
- These data are available via a Web API
- ARGO can alert administrators about critical errors etc.

While I cannot say anything about technical details, here is the basic configuration workflow:
- In GOCDB, you set up your mesh including various service types (these are merely IDs)
- Each service/service endpoint is assigned to one of those service types
- Metrics and probes are created in POEM
- Using these, you create profiles that associate a given service type with a metric
- The gathered metrics can then be aggregated to tag a site as "healthy"

So this is how ARGO works. It still seems to be rather difficult and a bit cumbersome to configure, though.

**Comment by Daniel-WWU-IT** [comment]
Document (request for comment) on the whole GOCDB/ARGO topic:
https://docs.google.com/document/d/1S2qKOl_HasC0UpjNapuchJ6S_wxNVZXE16x-ClriPac/edit?usp=sharing

**Comment by labkode** [comment]
Document created, next steps for next Sprint.
